version: '3.9'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend_test
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      FLASK_APP: backend.py
      FLASK_ENV: development
      MICROSERVICE_URL: http://cloned_microservice:5001
    command: python /app/backend.py

  cloned_microservice:
    build:
      context: .
      dockerfile: CM_Docker.dockerfile
    container_name: cloned_microservice
    ports:
      - "8000:5001"
    command: ["dotnet", "ApiGateway.dll"]

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordgroup50
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=k6

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=passwordgroup50
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  default:
    driver: bridge

volumes:
  grafana-storage:
